### ISSUE TITLE
kein offizielles Add-On / no official add-on

### ISSUE THREAD

**Issue by wi-wissen** [OsiPog/bester.durchschnitt#1]
Wir freue uns über das Engagement mit dem Umgang mit unserer https://beste.schule/
Wir stellen Entwickler*innen gern Test-Accounts zur Verfügung und haben auch eine per OAuth nutzbare API.

Bitte stell doch hier und auf den Add-On-Seiten deutlich heraus, dass es sich um kein offizielles Add-On handelt.

Lehrer*innen können übrigens Durchschnitte berechnen und sehen. Auch ist beste.schule Englisch, sofern der Browser nicht auf Deutsch eingestellt ist.

**Comment by OsiPog** [comment]
Danke für das Feedback! Eine Anmerkung, dass es kein offizielles Add-On ist werde ich sofort hinzufügen. Das Add-On ist hauptsächlich für Schüler gedacht, da ich bemerkt habe, dass viele neben der beste.schule Webseite ihre eigene Noten-App haben um dort ihren Durchschnitt zu sehen.

Da das Add-On so gut wie fertig ist, brauche ich jetzt keine Test-Accounts mehr. Ich hatte online nachgeschaut ob es eine API gibt, aber keine gefunden. Gut zu wissen, dass es doch eine gibt. Umschreiben werde ich das Add-On aber nicht mehr. 

Dass beste.schule einen englischen Modus hat habe ich auf meinem Handy schon bemerkt, aber egal ob der Browser auf Deutsch oder auf Englisch ist, der Text auf der Startseite ist Deutsch, deswegen dachte ich, dass beste.schule Deutsch ist.
